### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by PeppeSco** [Lebourdais/3MAS#1]
First of all, I would like to express my appreciation for the work you’ve done on this project. I find it truly fascinating and believe it makes a significant contribution to its field.

However, I encountered a small issue. In the README file, the requirements.txt file is mentioned for installing the project dependencies, but it seems to be missing from the repository. Without this file, it’s challenging to set up the development environment and test the project as recommended.

I would be truly grateful if you could provide the file or guide me toward an alternative solution. I’m excited to have the opportunity to experiment with this project and delve deeper into its content.

Thank you in advance for your time and attention.

Best regards,
Peppe

**Comment by Lebourdais** [comment]
Thank you for your interest,
I pushed a version of the requirements that should allow training a model,
If you have other inquiries, don't hesitate to ask,
Best,
